Auth integration
rahul-400/TaskApp pull request #13
Opened 2020-07-21 13:04 UTC by rahul-400

2020-07-21 13:10 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/other/CachingInfo.java
> +    }
Need correction in caching param keys and has a mismatch in terms of input terms.

2020-07-21 13:15 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/other/CachingInfo.java
> +            return "Invalid credentials";
Create constant for string literals

2020-07-21 13:15 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/other/CachingInfo.java
> +        if(employee.getCompanyId()!=companyId){
NPE for null employee

2020-07-21 13:15 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/other/CachingInfo.java
> +        if(employee.getCompanyId()!=companyId){
!= is not right way to compare boxed types

2020-07-21 13:16 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/other/CachingInfo.java
> +        if(!employeeInfoUpdate.getPosition().isEmpty()){
employeeInfoUpdate npe

2020-07-21 13:18 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/other/CachingInfo.java
> +        return employeeRepo.save(employee);
try catch for unique constraint check against db error of employee_id

2020-07-21 13:20 UTC, sumitmundraoyo reviewed
remove .DS_Store files

2020-07-21 13:21 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/repo/CompanyRepo.java
>              " emp.project_id as project_id,emp.phone_number as phone_number,emp.current_add as current_add,emp.permanent_add as permanent_add from Employee emp" +
Use DSL wherever required.

2020-07-21 13:22 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/repo/CompanyRepo.java
>              " emp.project_id as project_id,emp.phone_number as phone_number,emp.current_add as current_add,emp.permanent_add as permanent_add from Employee emp" +
Try to do it with join column and fetchmode or may be implement a custom repo with criteria query with hibernate

2020-07-21 13:26 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/service/CompanyServiceImpl.java
>              e.printStackTrace();
e.printStackTrace() should be gone in all project

2020-07-21 13:33 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/service/CompanyServiceImpl.java
>          catch (Exception e){
remove try catch wherever applicable

2020-07-22 04:35 UTC, rahul-400 reviewed
check for NPE in addEmployee,updateEmployeeInfo,updateSalary

2020-07-22 04:38 UTC, rahul-400 reviewed
Remove excess of if, else condition.
Remove println message.

2020-07-22 04:43 UTC, rahul-400 reviewed
Can use constant string for BOOTSTRAP_SERVERS_CONFIG.
Use constant string.
consumerEmployeeInfo, kafkaEmployee NPE.
Extra if else condition, remove it.
addEmployee method EmployeeServiceImpl NPE can come.

2020-07-22 08:53 UTC, rahul-400 reviewed
Use string constants instead of returning string. 
Add log, remove println.
No need to do same check twice. Employee Controller-updateEmployee.SalaryController as well.
KafkaEmployee NPE.
check for errors in cachingInfo. Variable does not exists, caching annotation.

2020-07-22 09:23 UTC, rahul-400 commented on src/main/java/com/assignment/application/controller/CompanyController.java
>  }
Use string constants.

2020-07-22 09:23 UTC, rahul-400 commented on src/main/java/com/assignment/application/controller/EmployeeController.java
> +        return new ResponseEntity<>("Invalid Credentials", HttpStatus.BAD_REQUEST);
Reduce the number of if.

2020-07-22 09:23 UTC, rahul-400 commented on src/main/java/com/assignment/application/controller/SalaryController.java
>      }
no need of two if here.

2020-07-22 09:23 UTC, rahul-400 commented on src/main/java/com/assignment/application/kafka/KafkaConfig.java
> +        map.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
use string constant for localhost.

2020-07-22 09:23 UTC, rahul-400 commented on src/main/java/com/assignment/application/kafka/KafkaConsumerListener.java
> +        if (employee == null) {
kafkaEmployee NPE.

2020-07-22 09:23 UTC, rahul-400 commented on src/main/java/com/assignment/application/logging/ResponseLogging.java
>      }
use log instead of println

2020-07-22 09:23 UTC, rahul-400 commented on src/main/java/com/assignment/application/service/CachingInfo.java
> +    public String updateEmployeeInfo(String employeeId, Long companyId, EmployeeInfoUpdate employeeInfoUpdate){
companyName variable doesn't exists.

2020-07-22 09:23 UTC, rahul-400 commented on src/main/java/com/assignment/application/service/CompanyServiceImpl.java
>      }
use string constant.

2020-07-22 09:23 UTC, rahul-400 commented on src/main/java/com/assignment/application/service/DepartmentServiceImpl.java
> +            return null;
probable db error. Check for it.

2020-07-23 06:58 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/interceptor/AuthInterceptor.java
> +        super.preHandle(request, response, handler);
cross check the invocation of pre handle

2020-07-23 07:00 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/interceptor/AuthInterceptor.java
> +        else if(userName.equalsIgnoreCase("admin") && password.equalsIgnoreCase("admin")){
static credentials in repo is a security threat

2020-07-23 07:00 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/interceptor/AuthInterceptor.java
> +        String password = request.getHeader("password");
store passwords in database in encrypted format

2020-07-23 07:02 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/interceptor/AuthInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
try to leverage http methods of 401 and 403 and throw exception there

2020-07-24 04:44 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/Constants/StringConstants.java
> +public class StringConstants {
Make this class a singleton with private constructor. No need to make a bean as well. :)

2020-07-24 04:45 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/test/CompanyServiceTest.java
> +    private StringConstants stringConstants;
It is a static constant reference, no need to mock something where there is no behaviour to be mocked.

2020-07-24 04:46 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/test/CompanyServiceTest.java
> +        //assumption company exists and company update json is not null
Incorrect way of testing. You have put the method under test in when clause. Then, in essence, no behaviour is getting tested here.

2020-07-24 04:46 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/test/CompanyServiceTest.java
> +        //assumption company exists and company update json is not null
Applies to all tests written here. Please redo them all

2020-07-24 04:48 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/test/CompanyServiceTest.java
> +        //assumption company exists and company update json is not null
A typical test could be to check against null behaviour from repo. Or say, deleting or updating something that does not exist, or say finding something that exists as successful behaviour for success cases. There can be a lot many tests added.

2020-07-24 04:49 UTC, sumitmundraoyo requested changes
Please redo tests

2020-07-24 04:55 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/service/CompanyServiceImpl.java
> +        return stringConstants.invalidStatus;
We can refer the static constants without instance object

2020-07-24 04:55 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/service/CompleteCompInfoImpl.java
> +        return completeCompInfos.stream().distinct().collect(Collectors.toList());
need simplification

2020-07-24 04:56 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/service/CompleteCompInfoImpl.java
> +//        predicate.add(criteriaBuilder.equal(employeeDepartmentJoin.get("companyId"),companyId));
Remove comments out of final code wherever you find them. We can always look up git history if there is a code which we want to refer later.

2020-07-24 04:58 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/service/EmployeeServiceImpl.java
> +        Employee employeeTemp = cachingInfo.addEmployee(employee,companyId);
Save to repo first, and then cache the object, so that you have the right entity id in cached object.

2020-07-27 09:07 UTC, sumitmundraoyo requested changes

2020-07-27 09:07 UTC, sumitmundraoyo commented on pom.xml
> +<!--        </dependency>-->
remove comments

2020-07-27 09:07 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/controller/ProjectController.java
> +    private VerifyUser verifyUser;
VerifyUser, seems to me like a value object, not a service. This is sort of a authentication helper.

2020-07-27 09:07 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/controller/ProjectController.java
> +            int status = verifyUser.authorizeUser(username, password);
Or instead we could have written a controller advice with exception handling for auth errors

2020-07-27 09:07 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/controller/SalaryController.java
> +    public final String TOPIC = "SalaryUpdate";
rename TOPIC to SALARY_UPDATE_TOPIC. topic does not convey meaning in code

2020-07-27 09:07 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/controller/SalaryController.java
> +                if (salary == null) {
This is not a bad request scenario. It is possible in correct cases as well. Just the salary info is yet to be uploaded.

2020-07-27 09:07 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/controller/SalaryController.java
> +                kafkaTemplateSalary.send(TOPIC, salaryUpdate);
I would love to see kafka triggers in service layer rather than controller layer to keep it view specific

2020-07-27 09:07 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/kafka/KafkaConfig.java
> +            return null;
log the error at the least

2020-07-27 09:07 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/kafka/KafkaConsumerListener.java
> +            e.printStackTrace();
no printing stack trace

2020-07-27 09:07 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/service/CachingInfo.java
> +            throw new RuntimeException(e.getMessage());
catching a runtime exception is hazard to app

2020-07-27 09:07 UTC, sumitmundraoyo commented on src/main/java/com/assignment/application/service/CachingInfo.java
> +        if(employee==null || !employee.getCompanyId().equals(companyId)){
extract a method called validate update info request ? for better readability's sake

2020-07-27 10:08 UTC, sumitmundraoyo approved these changes

2020-07-27 10:12 UTC, merged